version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
  build:
    commands:
      - echo "Preparing AppSpec artifact"
      - export IMAGE_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/java-app-repo:latest"
      - jq --arg IMG "$IMAGE_URI" '.containerDefinitions[0].image=$IMG' taskdef.json > taskdef-updated.json
      - zip appspec.zip appspec.yaml taskdef-updated.json

artifacts:
  files:
    - appspec.zip
